services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    command: bash -c 'sleep 3 && npm start'
    ports:
      - 8080:8080

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./services/caddy/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - app

